### PR TITLE
Implementation of Filing date and experimental quarterly filings

### PR DESCRIPTION
**Pull request by sword134**
For testing purposes only. This version will not work as intended for quarterly API requests

### CODE REVIEW

**Comment by JerBouma** [comment]
Thanks for the PR, I've worked on some fixes to the code so that it is possible to correctly get the data. Please let me know if this works! See related files:

- [Dataset (2).xlsx](https://github.com/JerBouma/FinanceToolkit/files/12165466/Dataset.2.xlsx)
- [Result (1).xlsx](https://github.com/JerBouma/FinanceToolkit/files/12165468/Result.1.xlsx)

**Comment by JerBouma** [comment]
This might also fix #44. Can you test for that?

**Comment by sword134** [comment]
I've commited some changed to saving the filing date. It only works for the get_income_statement() function for now. But is easily copy pasted onto balance and cash flow if approved.

**Comment by sword134** [comment]
> My thinking is to create a separate function that creates a DataFrame including Cid ID, Filing Date etc (general statistics)
> 
> This function uses the same API call as for each financial statement and automatically collects and saves that data as well so that you don't need two API Calls.
> 
> Let's do that separately from this PR, therefore I'd recommend reverting the change to add filing date.

Ok. The commit you made works for the intended purposes of quarterly statements. The only addition I have for that is the minor change in balance.csv where there is a duplicate of Minority Interest

**Comment by JerBouma** [comment]
Great, place reverse the filling dates code and then I can merge it in. After creating a separate function for the statistics data we can create a new version.

**Pull request merged**
